/*
 * Grady Landers
 * Master's Project - Code name Rubber Duck
 * code exporter super class
 */
package export;

import java.io.FileWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

abstract class CodeExport {
	//write opening block comment
	protected static void generateHeader(FileWriter f, String message) {
		try {
			f.append("/*\n * Code auto generated by the Rubber Duck programming tool on " + getNowString()
					+"\n * " + message
					+"\n */"
					+"\npackage output;\n\n");
		}
		catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	//write imports
	protected static void generateImports(FileWriter f, String[] imports, String className) {
		try {
			for(int i=0; i<imports.length; i++) {
				f.append("import " + imports[i] + ";\n");
			}
			f.append("\npublic class "+className+" {\n");
		}
		catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	//get current datetime modified from https://www.javatpoint.com/java-get-current-date
	protected static String getNowString() {
		DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
		LocalDateTime now = LocalDateTime.now();
		return dtf.format(now); 
	}
	
	//generate static variables for array program
	protected static void generateArrayVariables(FileWriter f, String type, Object[] arr, boolean num, Object target) throws Exception {
		try {
			f.append("\t//variables\n"
					+"\tstatic "+type+"[] arr = {");
			for(int i=0; i<arr.length; i++) {
				if(num) f.append(arr[i].toString());
				else f.append('"'+arr[i].toString()+'"');
				if(i < arr.length-1) f.append(",");
			}
			f.append("};\n");
			
			if(target != null) {
				String t;
				if(num) t = target.toString();
				else t = '"'+target.toString()+'"';
				f.append("\tstatic "+type+" target = "+t+";\n");
			}
			
			f.append("\n");
		}
		catch(Exception e) {
			throw e;
		}
	}
}
